### ISSUE TITLE
Unspecified errors occurred

### ISSUE THREAD

**Issue by krystalcode** [dcos/packet-terraform#4]
Installed terraform, cloned packet-terraform, configured vars. When I do "terraform apply", I get:

```
Error applying plan:

2 error(s) occurred:

* packet_device.dcos_master: 
* packet_device.dcos_bootstrap: 

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Not very informative error message so I don't know what is wrong really. Any ideas?

**Comment by jgarcia-mesosphere** [comment]
Hey there, would you post your `terraform.tfvars` (obscure secrets, please) and paste that up for me to take a look?

**Comment by krystalcode** [comment]
`packet_api_key` = "some-api-key"
packet_project_id = "some-project-id"
packet_facility = "sjc1"
packet_agent_type = "baremetal_0"
packet_master_type = "baremetal_0"
packet_boot_type = "baremetal_0"
dcos_cluster_name = "packet-dcos"
dcos_master_count = "1"
dcos_agent_count = "1"
dcos_public_agent_count = "1"
dcos_installer_url = "https://downloads.dcos.io/dcos/EarlyAccess/dcos_generate_config.sh"
dcos_ssh_key_path = "./packet-key"
dcos_ssh_public_key_path = "packet-key.pub"`

I have generated the keys, I have also tried different datacenters, different nodes of nodes incl. with the defaults (3, 4, 3), always getting the same error.

**Comment by adersberger** [comment]
same here with a little bit more error details:

2 error(s) occurred:

* packet_device.dcos_bootstrap: Project must have at least one SSH key
* packet_device.dcos_master: Project must have at least one SSH key

**Comment by zsmith928** [comment]
This doesn't look to be an issue with the Terraform vars or provider, but simply that you need to ensure you've configured your Packet account appropriately by adding in your public SSH key to your profile in the Packet.net interface.  Once you've done that, please re-test and it should just work (tm).

**Comment by adersberger** [comment]
Perfect. Now it works for me. Update of DC/OS docs (https://dcos.io/docs/1.7/administration/installing/cloud/packet/https://dcos.io/docs/1.7/administration/installing/cloud/packet/) is maybe helpful to prevent others from running into this problem.

**Comment by adersberger** [comment]
I had the same problem like @krystalcode. Root cause: I used the packet.net project name and not the real project id (see "Settings" tab within packet.net) as packet_project_id parameter.

**Comment by jedisct1** [comment]
Just had the exact same problem. Thanks, @adersberger  :)

**Comment by anandkolli** [comment]
Guide me in resolving the below issue:
i am trying to create a server on packet.net but its failing with below error
sudo terraform apply
packet_device.testme: Creating...
  billing_cycle:    "" => "hourly"
  created:          "" => "<computed>"
  facility:         "" => "sjc1"
  hostname:         "" => "test1"
  locked:           "" => "<computed>"
  network.#:        "" => "<computed>"
  operating_system: "" => "ubuntu_16_04"
  plan:             "" => "baremetal_0"
  project_id:       "" => "008d19ce-e5f6-4aab-8f58-025355a363a8"
  state:            "" => "<computed>"
  updated:          "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* packet_device.testme: Not found

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by jimleitch01** [comment]
Hi, like the poster above said, you need to add your packet project ID to the tfvars file, the UUID like string, not the name.

So the top of my tfvars file looks a bit like this:

==========================================
packet_api_key = "xxxxtWmXiB9aLicSevrpa9bQGKyyyy"
packet_project_id = "d83md73n-d84g-d8r0-d94l-xxxxxxxxxxxxx"
packet_facility = "ewr1"
packet_agent_type = "baremetal_2"
packet_master_type = "baremetal_2"
packet_boot_type = "baremetal_2"
dcos_cluster_name = "packet-dcos"
