### ISSUE TITLE
terraform apply never completes master

### ISSUE THREAD

**Issue by ahaurw01** [dcos/packet-terraform#8]
A number of times I tried following the official docs and `terraform apply` resulted in an infinite chain of 

```
packet_device.dcos_master: Still creating... (XXs elapsed)
```

When I `ctrl-c` out of it, an error appears:

```
* Failed to read key "./packet-key": no key found
```

I am using the default settings and have created the ssh key as instructed. I see from https://github.com/hashicorp/terraform/issues/8963 that this is no longer supported:

```
private_key = "${"file-name"}"
```

and this is to be used instead:

```
private_key = "${file("file-name")}"
```

After making this change, `terraform apply` completes.

**Comment by crunchywelch** [comment]
merged, thanks @ahaurw01

**Comment by ahaurw01** [comment]
You bet. Thank you, @crunchywelch!

**Comment by vbnospace** [comment]
private_key = "${file("file-name")}" still having the infinite chain. Please can anyone help me?
